### ISSUE TITLE
WooCommerceを有効化している環境でGianismを有効化するとエラーが発生し、管理画面にアクセスできなくなります。

### ISSUE THREAD

**Issue by yutaka12** [fumikito/Gianism#100]
表題の通り、WooCommerceとGianismを併用しようとするとエラーが発生し、管理画面にアクセスできなくなります。

各バージョンは以下の通り
Wordpress: 5.5.1–ja
WooCommerce: 4.5.2
Gianism: 4.3.1

エラーログ
Fatal error: Uncaught Error: Call to a member function get() on null in /var/www/html/wp-content/plugins/gianism/app/Gianism/Notices/WooCompatible.php:30
Stack trace:
#0 /var/www/html/wp-content/plugins/gianism/app/Gianism/Pattern/AbstractNotice.php(56): Gianism\Notices\WooCompatible->has_notice()
#1 /var/www/html/wp-includes/class-wp-hook.php(287): Gianism\Pattern\AbstractNotice->register_notice('')
#2 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /var/www/html/wp-admin/admin.php(175): do_action('admin_init')
#5 /var/www/html/wp-admin/plugins.php(10): require_once('/home/beigegoat...')
#6 {main}
  thrown in /var/www/html/wp-content/plugins/gianism/app/Gianism/Notices/WooCompatible.php on line 30

**Comment by fumikito** [comment]
@yutaka12 失礼しました。修正します。

**Comment by fumikito** [comment]
@yutaka12 4.3.2にアップデートし、エラーを解消しました。ご確認いただけますと幸いです。

**Comment by yutaka12** [comment]
@fumikito ご対応ありがとうございます。アップデートすることで無事利用することができました！
