### ISSUE TITLE
LINEログインで発生しているエラーについて

### ISSUE THREAD

**Issue by Shotaro-Tsutsumi** [fumikito/gianism#118]
初めまして。コメント失礼します。現在運用しているWordpressのサイトでGianism(LINEログイン)を使用させていただいているのですが、2日前あたりからLINEログイン時に「”kid” empty, unable to lookup connect key 」と表示されログインができないバグが発生しており、解決策が見つからない状況です。何か手がかりになる解決策がありましたらお力添えいただけると幸いです。サイト運用初心者のため、初歩的な質問で申し訳ありませんが、ご回答の程よろしくお願いいたします。

**Comment by RyoWakabayashi** [comment]
初めまして。
当方Gianismを使ったLINEログインを導入検討中で、検証中に同様のエラーが発生しております。
ご回答いただけると助かります。

**Comment by fumikito** [comment]
確認してみます。しばしお待ちを。

**Comment by free-leaf** [comment]
はじめまして。
昨日プルリクエストを出しておきましたが、Line.phpのコードを2箇所変更するとLINEログインでエラーが出なくなります。

プルリクエストした修正箇所は下記で確認できます。
https://github.com/fumikito/gianism/pull/119/commits/8f7cbe6eb5813a26109f5becdb2a57d921e3d24e

検証＆マージ待ちですが、サイトの復旧を急ぐようでしたら上記コードを試していただくとよいかもしれません。

**Comment by Shotaro-Tsutsumi** [comment]
上記コードで復旧することができました。
ありがとうございました。
