### ISSUE TITLE
Error - Sorry, but wrong access. Please go back

### ISSUE THREAD

**Issue by sinofanger** [fumikito/Gianism#50]
I am getting this error when I try to login using social network.

I already tried deactivating all other plugins and Cloudflare, but the problems is still there.

Please help. :(

![screenshot_2](https://cloud.githubusercontent.com/assets/9476430/7061852/777e217e-deb4-11e4-8766-450a245d32a6.png)

**Comment by fumikito** [comment]
@sinofanger 

Does your environment supports [$_SESSION](http://php.net/manual/en/session.examples.basic.php)?

This error means that plugin fails to retrieve the task to do.

Please check if your server supports session.

Try uploading this script as http://worldanimeclub.com/session.php and check if number counts up as reloading.

```php
<?php
// Starting session
session_start();
if( !isset($_SESSION['number']) ){
    $_SESSION['number'] = 0;
}
// Increment it
$_SESSION['number']++;
// If session enabled, this number will be increment as loading.
echo $_SESSION['number'];
```

Or else, If cache engine is enabled, exclude path below from caching.

- /facebook
- /twitter

**Comment by sinofanger** [comment]
Hi, I cleared the cache and the problem has been fixed. 

Now everything is working but can you please tell me how I can show the buttons inside the comment form. It is said that I should add this code:

if(function_exists('gianism_login')){
    gianism_login();
}

But where in comments.php should i add it?
![screenshot_3](https://cloud.githubusercontent.com/assets/9476430/7063481/d0ef1f8c-dec4-11e4-9f30-dab7ee9a4e09.png)

**Comment by fumikito** [comment]
@sinofanger 

> But where in comments.php should i add it?

It depends.

Suppose that your theme is based on 2015, comments.php is like [this](https://themes.svn.wordpress.org/twentyfifteen/1.0/comments.php).

In comments.php, the function `comment_form ()` is invoked.

Opening it, you will find some difficulty. It's very complicated. If you are experienced devloper, open `wp-includes/comment-template.php` and you'll know what to do.

Else, copy and paste this to your functions.php.

```php
// This action is called after the notice which your comment form display 
// when your user is not logged in.
add_action("comment_form_must_log_in_after", 'gainism_login');
```

I don't try, but it may work.
